baseURL       = "https://brandonwolfgang.com/"
enableGitInfo = false
languageCode  = "en-us"
relativeURLs  = true
theme         = "hugo-resume"
title         = "Brandon Wolfgang"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle                 = "monokai"

[params]
	address      = "Hemlock, MI"
	email        = "jobs@brandonwolfgang.com"
	favicon      = "/favicon.ico"
	firstName    = "Brandon"
	lastName     = "Wolfgang"
	phone        = "1-989-245-5096"
	profileImage = "images/avatar.png"
	sections     = ["skills","experience","education"]
	showAddress  = false
	showContact  = false
	showQr       = true
	showSocialLinks = true


[[params.handles]]
	link = "https://www.linkedin.com/in/brandonwolfgang/"
	name = "LinkedIn"

[[params.handles]]
	link = "https://github.com/brandonwolfgang/"
	name = "GitHub"

# [[params.handles]]
# link = "https://open.spotify.com/user/brandonwolfgang/"
# name = "Spotify"

# [[params.handles]]
# link = "https://bitbucket.org/eddiewebb/"
# name = "Bitbucket"

# [[params.handles]]
# link = "https://stackoverflow.com/users/story/82880"
# name = "Stack Overflow"

# [[params.handles]]
# link = "https://keybase.io/edwardawebb"
# name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"